services:
  localdb:
    image: postgres:15.1 # you can pick the most recent version available
    ports:
      - "5441:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  testdb:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - "POSTGRES_USER=${DB_USER_TEST}"
      - "POSTGRES_PASSWORD=${DB_USER_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME_TEST}"