version: '3.8'

services:
  localdb:
    image: postgres:15.1 
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env

  testdb:
    image: postgres:15.1
    ports:
      - "${DB_PORT_TEST}:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASSWORD_TEST}
      - POSTGRES_DB=${DB_NAME_TEST}
    env_file:
      - .env
